# Generated by Django 4.2 on 2023-04-28 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('country', models.CharField(default='india', max_length=200)),
                ('website', models.URLField(default='url')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('avatar', models.ImageField(upload_to='avatars/')),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name of the products')),
                ('mrp', models.IntegerField(verbose_name='MRP')),
                ('selling_price', models.IntegerField()),
                ('discount_percent', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('qty', models.PositiveIntegerField(verbose_name='quantity')),
                ('image_link', models.URLField()),
                ('color', models.CharField(max_length=20)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapi.brand')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapi.category')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('Products_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productsapi.products')),
            ],
        ),
    ]
